"""users table

Revision ID: ddbaae1cd1dc
Revises: 
Create Date: 2019-09-28 11:48:04.269789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbaae1cd1dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'created',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
